services:
    db:
        image: mariadb:11
        container_name: ordenavia-db
        restart: always
        volumes:
            - mariadb_data:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
        healthcheck:
            test: [ "CMD-SHELL", "mariadb -hlocalhost -u${DB_USER} -p${DB_PASSWORD} -e 'SELECT 1;' ${DB_NAME}" ]
            interval: 5s
            timeout: 10s
            retries: 5
        networks:
            - ordenavia-net

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        volumes:
            - ${PROJECT_PATH}/backend/ordenavia/:/app
        env_file:
            - ${PROJECT_PATH}/backend/.env
        ports:
            - "${DJANGO_PORT}:8000"
        depends_on:
            db:
                condition: service_healthy
        networks:
            - ordenavia-net
        command: python manage.py runserver 0.0.0.0:8000

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ${PROJECT_PATH}/frontend/ordenavia/:/app
            - /app/node_modules
        env_file:
            - ${PROJECT_PATH}/frontend/.env
        ports:
            - "${REACT_PORT}:5173"
        depends_on:
            db:
                condition: service_healthy
        networks:
            - ordenavia-net
        command: yarn run dev --host

volumes:
    mariadb_data:

networks:
    ordenavia-net:
        driver: bridge
